name: Pipeline
on:
  push:
    branches:
      - master
jobs:
  format-and-lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust dependencies
        uses: moonrepo/setup-rust@v1

      - name: Run cargo fmt
        run: cargo fmt --verbose --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run cargo test
        run: cargo test --verbose
